### ISSUE TITLE
Upload key to key server

### ISSUE THREAD

**Issue by datawookie** [jeroenooms/gpg#10]
Hi @jeroen, really love working with `{gpg}`. I see that there's a function to receive keys from a key server, `gpg_recv()`, but no corresponding function to send keys to a key server. Would you be open to a PR implementing this functionality? Thanks, Andrew.

**Comment by jeroen** [comment]
Yes go for it :)

**Comment by datawookie** [comment]
PR submitted.

**Comment by datawookie** [comment]
Closed by https://github.com/jeroen/gpg/pull/11.
