### ISSUE TITLE
Can't delete secret keys

### ISSUE THREAD

**Issue by karawoo** [jeroenooms/gpg#3]
I can't seem to delete secret keys with the gpg package. Here's a reprex:

``` r
library("gpg")
#> Found GPG 2.2.3. Using keyring: /Users/Kara/.gnupg

key <- gpg_keygen("test", "test@test.test")
secret_id <- gpg_list_keys("test", secret = TRUE)$id

gpg_delete(secret_id, secret = TRUE)
#> [1] "A69020A02D7CA8A3"

gpg_list_keys("test") # key is still there
#>                 id                              fingerprint name
#> 1 A69020A02D7CA8A3 86739F3FDEDFFBC5555D4F6EA69020A02D7CA8A3 test
#>            email algo           timestamp             expires
#> 1 test@test.test  RSA 2018-05-23 09:06:28 2020-05-22 09:06:28
```

Created on 2018-05-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

However if I delete the secret key from the command line, I can then delete the public key from R.

<details>
<summary>Session info</summary>
<pre><code>
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gpg_0.5            reprex_0.2.0       testthat_2.0.0     usethis_1.3.0.9000
[5] devtools_1.13.5   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17     rprojroot_1.3-2  crayon_1.3.4     assertthat_0.2.0
 [5] digest_0.6.15    withr_2.1.2      R6_2.2.2         backports_1.1.2 
 [9] magrittr_1.5     evaluate_0.10.1  stringi_1.2.2    rlang_0.2.0.9001
[13] callr_2.0.4      whisker_0.3-2    rmarkdown_1.9    tools_3.5.0     
[17] stringr_1.3.1    compiler_3.5.0   processx_3.1.0   clipr_0.4.0     
[21] htmltools_0.3.6  memoise_1.1.0    knitr_1.20      
</code></pre>

</details>

**Comment by jeroen** [comment]
Thanks! Are you using the cran version of the package or did you install from source?

**Comment by karawoo** [comment]
I'm using the CRAN version

**Comment by jeroen** [comment]
Can you try if it makes any difference if you install from source?

```
brew install gpgme
```
```r
install.packages("gpg", type = "source")
```

**Comment by karawoo** [comment]
Nope, it's the same when I install from source

**Comment by jeroen** [comment]
Hmm this seems to be a bug in gpgme when using gnupg2. It does not appear when we use the cran version with only gpg1:

```r
brew unlink gnupg
```

And then `install.packages("gpg", repos = "https://cloud.r-project.org")`. I'm going to ask on the gnupg mailing list...

**Comment by jeroen** [comment]
Fixed in https://github.com/jeroen/gpg/commit/ee00b05f0354aa01c5fe1c4e7672e56be998498a
