### ISSUE TITLE
Decrypt serialized R object 

### ISSUE THREAD

**Issue by jmueller17** [jeroenooms/gpg#5]
I posted this issue on [stackoverflow](https://stackoverflow.com/questions/52599132/encrypt-decrypt-object-in-r-with-librarygpg?noredirect=1#comment92133186_52599132), but with little success. Since this is related to gpg library, maybe Jeroen can help? I encrypt a serialized data frame. 

```library(gpg)
df <- data.frame(A=c(1,2,3), B=c("A", "B", "C"), C=c(T,F,F)) 
df <- serialize(df, con=NULL, ascii=T) 
enc <- gpg_encrypt(df, receiver="your_key_here") 
writeBin(enc, "test.df.gpg")
```

But I can't decrypt it, or rather I can decrypt but gpg_decrypt() delivers a sequence of plain characters from which it is impossible to restore the original data frame. 

```
dec <- gpg_decrypt("test.df.gpg") 
df <- unserialize(dec) #throws error ! 
```

The encrypted file is ok. I can decrypt manually on the command line and then restore the original R dataframe with readRDS(). But not via the `gpg_decrypt()` function? Any thoughts?

**Comment by jeroen** [comment]
It looks like I was assuming text data before. I have added an argument `as_text` to `gpg_decrypt()` so you should be able to do:

 ```r
gpg_decrypt("test.df.gpg", as_text = FALSE)
```

and then get raw output.

**Comment by jmueller17** [comment]
Thank you! Now it works perfectly.
