### ISSUE TITLE
Using {gpg} on GitHub Actions with macOS

### ISSUE THREAD

**Issue by datawookie** [jeroenooms/gpg#9]
Hi @jeroen,

I am having trouble using `{gpg}` on GitHub Actions with macOS.

For context, here is the content of the script that I'm running:

```r
library(gpg)

print(gpg_version())

gpg_keygen(name = "Alice", email = "alice@yahoo.com")
```

I'm generating a keypair for use in testing on `{emayili}`.

**Ubuntu**

On Ubuntu (which I'm also running locally) this runs fine.

**macOS**

But on macOS it breaks.

```
gpg (GnuPG) 2.3.3
libgcrypt 1.9.4
Copyright (C) 2021 Free Software Foundation, Inc.
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/runner/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
AEAD: EAX, OCB
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
 [1] "gpg (GnuPG) 2.3.3"                                                 
 [2] "libgcrypt 1.9.4"                                                   
 [3] "Copyright (C) 2021 Free Software Foundation, Inc."                 
 [4] "License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>"  
 [5] "This is free software: you are free to change and redistribute it."
 [6] "There is NO WARRANTY, to the extent permitted by law."             
 [7] ""                                                                  
 [8] "Home: /Users/runner/.gnupg"                                        
 [9] "Supported algorithms:"                                             
[10] "Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA"                         
[11] "Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,"
[12] "        CAMELLIA128, CAMELLIA192, CAMELLIA256"                     
[13] "AEAD: EAX, OCB"                                                    
[14] "Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224"             
[15] "Compression: Uncompressed, ZIP, ZLIB, BZIP2"                       
══ Skipped tests ═══════════════════════════════════════════════════════════════
• On CI (2)
• suppressWarnings(is.na(smtp_gmail)) is TRUE (1)

══ Failed tests ════════════════════════════════════════════════════════════════
── Error (test-encrypt.R:20:1): (code run outside of `test_that()`) ────────────
Error: Error: GPGME create key error: General error
Backtrace:
    █
 1. └─gpg::gpg_keygen(name = "Alice", email = "alice@yahoo.com") test-encrypt.R:20:0
```

My first suspicion is that this might be a problem with the version of GPG (I see that it's 2.3.3 on macOS and I've only got 2.2.19 locally). I did read somewhere that the default key type used in GPG is different in 2.3.3. Another possibility is that macOS is trying to get a passphrase via a user prompt in a non-interactive session.

I hope that you have some ideas around what the problem might be. Feel free to make suggestions for things that I could test to provide more information.

Thanks, Andrew.

**Comment by jeroen** [comment]
I'm seeing this also locally with the gpg 2.3 on macos. It does not happen icw gpg 2.2 indeed. Maybe they changed the keygen api again, the `gpg_keygen()` function already uses 2 different keygen apis. Or perhaps a passhprase is now mandatory? This seems to work:

```r
gpg_keygen(name = "Alice", email = "alice@yahoo.com", passphrase = "test")
```

**Comment by jeroen** [comment]
I have pushed a small fix, can you test if that works for you?

I also found out that the keygen function may give an error that about not finding gpg-agent when you run gpg in a custom home dir (using gpg_restart). Probably it needs the `/.gnupg/S.gpg-agent` socket link?

**Comment by datawookie** [comment]
Thanks for responding to this issue so quickly, @jeroen! Really appreciate it. Will try that out now and let you know.

**Comment by jeroen** [comment]
OK thanks. If it works I can send it of to CRAN.

**Comment by datawookie** [comment]
Hi @jeroen, yes, indeed, it seems to work very well! :) Thanks so much for the quick fix. :+1: Please send it off to CRAN! Best regards, Andrew.

![image](https://user-images.githubusercontent.com/6134409/144786354-4d437689-adf3-40c7-88b0-945698c77271.png)

**Comment by jeroen** [comment]
OK I've submitted it to cran
